모든 상품 조회 기능 추가
prgrms-be-devcourse/BEDV1_CREAM pull request #15
Opened 2021-10-29 09:56 UTC by buri-1029

- 조회 기능을 관리자, 사용자 공통으로 사용하기위해 두 컨트롤러에서 ProductService 의존성 주입
- [코드](https://github.com/prgrms-be-devcourse/BEDV1_CREAM/pull/15/files#r739105984) 해당 상품의 즉시 구매가(구매가 중 최저값), 즉시 판매가(판매가 중 최고값)를 가져오기 위한 로직을 구현하는 부분을 깔끔하게 리팩토링하고 싶은데 지금 방법이 최선이네요...

2021-10-30 05:08 UTC, LSH0809 approved these changes
부리님 조회 기능 작성하시느라 고생하셨습니다!! 조회 기능 작성하느라 힘들어했던게 보였는데... 이렇게 작성하신거 보니 너무 멋있습니다ㅎㅎ 남은 1주일도 파이팅해요!!

2021-10-30 05:08 UTC, LSH0809 commented on src/main/java/org/prgrms/cream/domain/product/controller/AdminController.java
> +
저는 음.. 중복코드가 많이 나오는 것이 아니니까 이대로 유지하는게 괜찮지 않을까 싶어요!! 중복된 부분이 있긴 하지만 많은 부분이 관리자와 사용자를 분리하는 것이 주체에 대한 구분이 좀 더 명확하게 되지 않나~ 싶습니다! 🤔

2021-10-30 09:16 UTC, buri-1029 commented on src/main/java/org/prgrms/cream/domain/product/service/ProductService.java
> +	}
아 제가 더 설명은 안했네용! PR 내용에서 두번째 부분의 코드입니당😆

2021-10-30 09:20 UTC, buri-1029 commented on src/main/java/org/prgrms/cream/domain/product/controller/AdminController.java
> +
오오 이유까지 들어서 좋은 답이네요!! 고맙슴당🤭 저도 관리자의 기능들은 엔드포인트도 일관성있게 가는 것이 좋을 것 같아요. 그럼 그대로 가겠습니닷

2021-10-30 09:35 UTC, buri-1029 commented on src/main/java/org/prgrms/cream/domain/product/repository/ProductRepository.java
> +	List<Product> findAllByIsDeletedFalse();
꺄아😆 굳굳

2021-10-30 09:40 UTC, buri-1029 commented on src/main/java/org/prgrms/cream/domain/product/repository/ProductOptionRepository.java
> +	);
즉시 구매가에서 최저가를 구해야하는데 저희가 0을 디폴트 값을 넣었자나용 그래서 0인 값(아직 입찰 값이 등록되지 않음)을 제외할 수 있게하는 쿼리메서드 기능([참고](https://kururu.tistory.com/m/239) 이에용!!

2021-10-30 16:47 UTC, samkimuel requested changes
리뷰 중 팀원과 같이 얘기할 부분이 있어서 이후 다시 진행하시면 될 것 같습니다!

2021-10-30 16:47 UTC, samkimuel commented on src/main/java/org/prgrms/cream/domain/product/service/ProductService.java
>  	private Product findActiveProduct(Long id) {
```suggestion
	public Product findActiveProduct(Long id) {
```

이 메서드가 나중에 다른 서비스 로직에서도 쓰일 것 같은 생각이 들었어요(User 에서도 똑같은 이슈(?)가 있었어요!)
그래서 public으로 만들어줘도 좋을 것 같다는 생각을 했습니다!
아니면 지금은 그대로 두고 나중에 그런 이슈가 발생한다면 수정하는 것도 괜찮을 것 같네요
부희님은 어떻게 생각하시나요??

2021-10-30 16:47 UTC, samkimuel commented on src/main/java/org/prgrms/cream/domain/product/service/ProductService.java
> +	}
Optional.empty() 를 어떻게 DTO에 만들어 넣을지 대한 부분이군요,,,

제가 생각한 부분은
- DTO에 Optional.empty() 처리 행위를 추가해서 해당 필드를 특정 값으로 정하기
- 특정 값으로 정한다면 어떤 값으로 정할지 -> 필드를 Nullable 로 / int면 0 으로 만들기

이건 저희 팀 같이 어떻게 해야할지 고민해봐야겠는데요? 컨벤션이 될 것 같습니다!

2021-10-30 18:49 UTC, buri-1029 commented on src/main/java/org/prgrms/cream/domain/product/service/ProductService.java
>  	private Product findActiveProduct(Long id) {
네! 구매와 판매 쪽에서 상품과 관계있느니 해당 상품이 존재하는지 확인하는 메서드를 사용하겠군요!! 다른 서비스와 공유하고 기본 기능이 아닌 확인하는 용도의 메서드니니 그런 부분도 구분지어줄 겸`protected` 접근 제어자를 사용하는 것이 어떨까요?

2021-10-30 19:25 UTC, buri-1029 commented on src/main/java/org/prgrms/cream/domain/product/service/ProductService.java
> +	}
네 좋아요! 이야기해보고 적용시켜보겠습니닷🧚‍♀️

2021-10-31 12:56 UTC, samkimuel requested changes
고생하셨습니다!!
코멘트 간단히 확인해주세요🙂

2021-10-31 12:56 UTC, samkimuel commented on src/main/java/org/prgrms/cream/domain/product/service/ProductService.java
> +	public Product findActiveProduct(Long id) {
```suggestion
        @Transactional(readOnly = true)
	public Product findActiveProduct(Long id) {
```

@Transactional 어노테이션을 붙여주면 좋을 것 같습니다!

2021-10-31 12:56 UTC, samkimuel commented on src/main/java/org/prgrms/cream/domain/product/service/ProductService.java
> +	}
전보다는 확실히 깔꼬롬해졌네용👍🏻

2021-10-31 13:02 UTC, buri-1029 commented on src/main/java/org/prgrms/cream/domain/product/service/ProductService.java
> +	}
0c8803a

2021-10-31 13:04 UTC, buri-1029 commented on src/main/java/org/prgrms/cream/domain/product/dto/ProductsResponse.java
> +	}
음 빈 객체 생성을 막기 위해 `private`으로 선언해도 될 것 같아요🤔

2021-10-31 13:06 UTC, samkimuel approved these changes

2021-10-31 13:07 UTC, buri-1029 commented on src/main/java/org/prgrms/cream/domain/product/service/ProductService.java
> +	public Product findActiveProduct(Long id) {
아 넵! 상세 조회 기능에서 수정하도록 하겠습니당😆

2021-10-31 13:09 UTC, merged