판매입찰등록기능 추가
prgrms-be-devcourse/BEDV1_CREAM pull request #21
Opened 2021-10-31 17:25 UTC by LSH0809

## 👩‍💻 요구 사항과 구현 내용 

- 기본적인 판매입찰등록 기능 구현
- 만약 이전에 같은 제품, 같은 사이즈, 같은 사용자에게 입찰이 등록된 기록이 있다면 마감기한과 가격을 업데이트
- 만약 이전에 판매입찰이 없다면 판매입찰을 생성
- 업데이트 혹은 생성을 할 때마다 가격 최신화 업데이트

## ✅ PR 포인트 & 궁금한 점 
- 깔끔하게 작성해보려고 노력은 했는데.. 그게 잘 안되었습니다.. 어떻게 바꾸면 좋을지 이야기해주시면 바꿔보도록 노력할게요!

2021-10-31 17:49 UTC, buri-1029 requested changes
밤늦게까지 수고하십니다 수형님😢
중복 코드부분에 대해서 고민해봅시댜

2021-10-31 17:49 UTC, buri-1029 commented on src/main/java/org/prgrms/cream/domain/deal/controller/SellingController.java
> +
```suggestion

```

2021-10-31 17:49 UTC, buri-1029 commented on src/main/java/org/prgrms/cream/domain/deal/service/SellingService.java
> +	}
이 두 메서드에서 중복 코드가 있으니 한 메서드에서 로직 처리(existsSameBid()를 여기서 처리) 해서 구현할 수 있을 것 같은데 수형님 생각은 어떠신가유??

2021-10-31 18:56 UTC, samkimuel requested changes
수형님 고생하셨습니다! 고민 많이 하시면서 구현하신게 느껴지네요!🙂
수형님 코드를 보면서 제 코드도 리팩토링 해야 할 부분이 많다는 걸 깨닫게 됐습니다😂
코멘트 몇 개 달았으니 확인해주세요!

2021-10-31 18:56 UTC, samkimuel commented on src/main/java/org/prgrms/cream/domain/deal/service/SellingService.java
> +			|| productOption.getLowestPrice() == 0) {
`0` 이 매직넘버네요! 따로 상수로 관리해주면 좋을 것 같습니다!

2021-10-31 18:56 UTC, samkimuel commented on src/main/java/org/prgrms/cream/domain/deal/service/SellingService.java
> +			|| productOption.getLowestPrice() == 0) {
여기도 매직넘버있네욥!
위의 리뷰랑 같이 상수로 표현할 수 있을 것 같아요!

2021-10-31 18:56 UTC, samkimuel commented on src/main/java/org/prgrms/cream/domain/deal/service/SellingService.java
> +		);
엔티티에서 변환하는건 어떨까요?? 저도 그렇게 한번 리팩토링해보려고 합니다!

2021-10-31 18:56 UTC, samkimuel commented on src/main/java/org/prgrms/cream/domain/deal/service/SellingService.java
> +	}
따로 메서드로 분리해주셔서 코드가 깔끔해졌네요!👍🏻
위에 리뷰에 이어서 이 부분도 같이 엔티티로 가져가면 어떨까 생각해봤습니다. 수형님은 어떻게 생각하시나요?

2021-10-31 18:56 UTC, samkimuel commented on src/main/java/org/prgrms/cream/domain/deal/controller/SellingController.java
> +			sellingService.registerSellingBid(id, size, bidRequest)));
저는 이 분기를 Controller에서 할지, Service에서 할지 고민🤔인데 수형님은 Contoroller에서 처리하셨군요!
저는 Service에서 구현해볼게요!

2021-11-01 13:25 UTC, LSH0809 commented on src/main/java/org/prgrms/cream/domain/deal/service/SellingService.java
> +	}
8386320 : BidResponse 응답객체를 엔티티에서 반환하면서 이 부분도 삭제 했습니다! 명환님 말씀대로 하니 코드가 좀 더 줄어들었어요!ㅎㅎ

2021-11-01 13:26 UTC, LSH0809 commented on src/main/java/org/prgrms/cream/domain/deal/controller/SellingController.java
> +			sellingService.registerSellingBid(id, size, bidRequest)));
넵!! 명환님 구현하시면 서로 거 비교하면서 다시 이야기 해봐요!!

2021-11-01 13:27 UTC, LSH0809 commented on src/main/java/org/prgrms/cream/domain/deal/service/SellingService.java
> +		);
명환님 말씀대로 하고 날짜 계산하는 메소드를 엔티티 내부에서 구현하니 훨씬 더 깔끔해진 것 같습니다!! SellingService에서 날짜 계산하는 메소드도 삭제했습니다!!

2021-11-01 13:27 UTC, LSH0809 commented on src/main/java/org/prgrms/cream/domain/deal/service/SellingService.java
> +			|| productOption.getLowestPrice() == 0) {
매직넘버... 확실히 알겠습니다!! 매직넘버라는 것을 이번에 알게 됐네요... ㅎㅎ 🙇

2021-11-01 13:30 UTC, LSH0809 commented on src/main/java/org/prgrms/cream/domain/deal/service/SellingService.java
> +			|| productOption.getLowestPrice() == 0) {
ffeb497 : 매직넘버 수정했습니다!!

2021-11-01 13:32 UTC, LSH0809 commented on src/main/java/org/prgrms/cream/domain/deal/controller/SellingController.java
> +
bf97918 : 수정했습니다!! 감사합니당!

2021-11-01 13:49 UTC, samkimuel approved these changes
고생하셨습니다👍🏻

2021-11-01 14:11 UTC, buri-1029 commented on src/main/java/org/prgrms/cream/domain/deal/service/SellingService.java
> +		return sellingBid.toBidResponse(bidRequest);
저는 처음에 생각했던 게 이 부분도 중복이니 두개의 메서드가 아니라 하나의 메서드에서 `existsSameBid()`을 작성해서 같은 값 유무에 따라 원래의 두 메서드에서 각각 달랐던 부분만(?) 구현해주면 되지 않을까 생각했습니다. 

이 부분은 더이야기해서 추후 리팩토링하는 것으로 합시당😆

2021-11-01 14:12 UTC, buri-1029 commented on src/main/java/org/prgrms/cream/domain/deal/service/SellingService.java
> +	}
[리뷰 작성](https://github.com/prgrms-be-devcourse/BEDV1_CREAM/pull/21/files#r740241480) 이걸로 봐주시면 될 것 같슴당

2021-11-01 14:12 UTC, buri-1029 approved these changes

2021-11-01 14:20 UTC, merged