회원판매내역 조회기능 추가
prgrms-be-devcourse/BEDV1_CREAM pull request #31
Opened 2021-11-02 11:11 UTC by LSH0809

- 회원 판매내역 조회기능
- 입찰, 결제내역을 status 상태에 맞게 조회
- 반환Dto에 각 항목에 대한 리스트가 담긴 dto 반환 담아서 전송

2021-11-02 12:12 UTC, buri-1029 requested changes
연관된 정보 가져오는 부분 어떠셨나요! 복잡하셨을텐데ㅠㅠ
잘 구현하셨습니닷 고생하셨습니닷!!

2021-11-02 12:12 UTC, buri-1029 commented on src/main/java/org/prgrms/cream/domain/deal/domain/SellingBid.java
> +		);
저는 dto의 생성자를 이용해서 변환하는 방법을 사용했는데 엔티티 안에 변환하는 메서드로 넣어서 구현했군용👀

2021-11-02 12:12 UTC, buri-1029 commented on src/main/java/org/prgrms/cream/domain/user/service/UserBidService.java
> +		}
다음에 시간이 된다면 제가 ProductService에서 구현했던 것처럼 stream().map()~ 을 사용해보는 것도 좋을 것 같아용

2021-11-02 13:53 UTC, LSH0809 commented on src/main/java/org/prgrms/cream/domain/deal/domain/SellingBid.java
> +		);
네!! 명환님이랑 이야기 했는데 이런 방식으로 하면 좋을 것 같다고 얘기 했어요!! ㅎㅎ 👋

2021-11-02 13:54 UTC, LSH0809 commented on src/main/java/org/prgrms/cream/domain/user/service/UserBidService.java
> +		}
그쵸!! 아.. stream을 써볼까 했는데 익숙치 않아서 못했습니당... 다음에 여유가 생긴다면 꼭 한번 써볼게요!! 👍

2021-11-02 13:55 UTC, LSH0809 commented on src/main/java/org/prgrms/cream/domain/user/controller/UserBidController.java
> +}
넵!!! 수정하도록 할게요! 👍

2021-11-02 19:17 UTC, LSH0809 commented on src/main/java/org/prgrms/cream/domain/deal/model/DealStatus.java
> +	PAYMENT_COMPLETED("결제 완료");
3fa44a6 : 수정했습니다!!

2021-11-02 19:28 UTC, LSH0809 commented on src/main/java/org/prgrms/cream/domain/user/service/UserBidService.java
> +		);
수정했습니당!!! 이 부분 구현하느라 오래 걸렸네요! ㅎㅎㅎ

2021-11-02 19:30 UTC, LSH0809 commented on src/main/java/org/prgrms/cream/domain/deal/model/DealStatus.java
> +	PAYMENT_COMPLETED("결제 완료");
3fa44a6 : 수정했습니당!! 👍

2021-11-02 19:31 UTC, LSH0809 commented on src/main/java/org/prgrms/cream/domain/user/domain/User.java
> +		static UpdateInfo getUpdateOption(String input) {
c2d27fa : 추가했습니다!!!

2021-11-02 20:40 UTC, buri-1029 approved these changes

2021-11-02 21:07 UTC, samkimuel requested changes
수형님 고생하셨어요! 끝까지 파이팅입니다!!!
저랑 로직이 겹치는 부분이 있어서 나중에 또 얘기해봐야할 것 같네요ㅋㅎㅎ,,, 페어해보죵

2021-11-02 21:07 UTC, samkimuel commented on src/main/java/org/prgrms/cream/domain/user/domain/User.java
> +				.filter(u -> u.option.equals(input))
`u` 가 의미가 불명확하니까 의미있는 표현으로 수정하면 좋을 것 같습니다!

2021-11-02 21:07 UTC, samkimuel commented on src/main/java/org/prgrms/cream/domain/user/dto/UserDealResponse.java
> +	private String status;
모든 필드가 생성자로 들어가있어서 final 붙여도 될 것 같네요!

2021-11-03 04:29 UTC, samkimuel commented on src/main/java/org/prgrms/cream/domain/user/service/UserBidService.java
> +		);
고생하셨슴다 !!

2021-11-03 06:36 UTC, LSH0809 commented on src/main/java/org/prgrms/cream/domain/deal/service/DealService.java
> +	}
52a2530 : 수정했습니다!! 알려주셔서 감사합니다!!

2021-11-03 06:38 UTC, LSH0809 commented on src/main/java/org/prgrms/cream/domain/deal/service/DealService.java
> +			userService.findActiveUser(id), status);
4b9b94e : 수정했습니당!! 훨씬 깔끔하네요!!!

2021-11-03 06:38 UTC, LSH0809 commented on src/main/java/org/prgrms/cream/domain/deal/service/SellingService.java
> +		return new SellingHistoryResponse(bidsToBidResponse(userSellingBidResponses, sellingBids));
ce2b5bf : 수정했습니다!!! 감사합니당!

2021-11-03 06:39 UTC, LSH0809 commented on src/main/java/org/prgrms/cream/domain/deal/service/SellingService.java
> +	}
b15e62e : 알려주셔서 감사합니다!!!

2021-11-03 06:43 UTC, LSH0809 commented on src/main/java/org/prgrms/cream/domain/user/domain/User.java
> +				.filter(u -> u.option.equals(input))
8b894db : 간단하게 표현하고자 이렇게 했는데 명환님 말씀처럼 변수의 의미가 불명확한 부분이 있네요!!

2021-11-03 06:43 UTC, LSH0809 commented on src/main/java/org/prgrms/cream/domain/user/dto/UserDealResponse.java
> +	private String status;
330526f : 알려주셔서 감사합니다!!! 수정했습니다! 👍

2021-11-03 06:47 UTC, samkimuel approved these changes
수정하느라 고생하셨습니다! 충돌 해결만 하면 되겠네요 ㅎㅎ

2021-11-03 07:18 UTC, merged